# Generated by Django 5.0.3 on 2024-03-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp', '0002_category_hostel_user_staff_student_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
