# Generated by Django 5.0.3 on 2024-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp', '0003_staff_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='delete_by_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='delete_by_student',
            field=models.IntegerField(default=0),
        ),
    ]
