# Generated by Django 5.0.3 on 2024-04-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp', '0004_complaint_delete_by_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room_no',
        ),
    ]
