# Generated by Django 5.0.3 on 2024-04-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp', '0006_remove_complaint_room_no_student_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='hostel',
        ),
    ]
