# Generated by Django 5.0.3 on 2024-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp', '0007_remove_complaint_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
